AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PACS Security proof-of-concept backend
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 256

Resources:
  PacsSecurityApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.main
      Policies: AWSLambdaBasicExecutionRole
      Events:
        GetDevices:
          Type: Api
          Properties:
            Path: /devices
            Method: get
        GetRules:
          Type: Api
          Properties:
            Path: /rules
            Method: get
        GetIncidents:
          Type: Api
          Properties:
            Path: /incidents
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /event
            Method: post
